
export const carBrands = [
  'Alfa Romeo',
  'Audi',
  'BMW',
  'Citroen',
  'Dacia',
  'Fiat',
  'Ford',
  'Honda',
  'Hyundai',
  'Kia',
  'Land Rover',
  'Mazda',
  'Mercedes',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Renault',
  'Seat',
  'Skoda',
  'Suzuki',
  'Toyota',
  'Volkswagen',
  'Volvo',
];

const carModels: Record<string, string[]> = {
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', 'Giulietta'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8'],
  'BMW': ['Série 1', 'Série 2', 'Série 3', 'Série 4', 'Série 5', 'Série 6', 'Série 7', 'Série 8', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7'],
  'Citroen': ['C1', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C5', 'C5 Aircross', 'Berlingo', 'SpaceTourer', 'Jumpy', 'Jumper'],
  'Dacia': ['Sandero', 'Duster', 'Logan', 'Spring', 'Jogger'],
  'Fiat': ['500', '500X', 'Panda', 'Tipo', 'Ducato', 'Doblo', 'Scudo'],
  'Ford': ['Fiesta', 'Focus', 'Kuga', 'Puma', 'Mustang', 'EcoSport', 'Explorer', 'Ranger', 'Transit', 'Transit Custom'],
  'Honda': ['Jazz', 'Civic', 'HR-V', 'CR-V', 'e'],
  'Hyundai': ['i10', 'i20', 'i30', 'Kona', 'Tucson', 'Santa Fe', 'Ioniq', 'IONIQ 5'],
  'Kia': ['Picanto', 'Rio', 'Ceed', 'Sportage', 'Niro', 'Sorento', 'EV6'],
  'Land Rover': ['Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Defender', 'Discovery', 'Discovery Sport'],
  'Mazda': ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'MX-5'],
  'Mercedes': ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'Classe S', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Sprinter', 'Vito'],
  'Mini': ['Cooper', 'Countryman', 'Clubman'],
  'Mitsubishi': ['Space Star', 'ASX', 'Eclipse Cross', 'Outlander', 'L200'],
  'Nissan': ['Micra', 'Juke', 'Qashqai', 'X-Trail', 'Ariya', 'Leaf', 'Navara', 'NV200', 'NV300', 'NV400'],
  'Opel': ['Corsa', 'Astra', 'Crossland', 'Grandland', 'Insignia', 'Combo', 'Vivaro', 'Movano'],
  'Peugeot': ['108', '208', '308', '408', '508', '2008', '3008', '5008', 'Partner', 'Expert', 'Boxer', 'Rifter', 'Traveller'],
  'Porsche': ['911', '718', 'Taycan', 'Panamera', 'Macan', 'Cayenne'],
  'Renault': ['Clio', 'Captur', 'Megane', 'Arkana', 'Austral', 'Kadjar', 'Espace', 'Kangoo', 'Trafic', 'Master', 'ZOE'],
  'Seat': ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco'],
  'Skoda': ['Fabia', 'Scala', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq'],
  'Suzuki': ['Ignis', 'Swift', 'Vitara', 'S-Cross', 'Jimny'],
  'Toyota': ['Aygo', 'Yaris', 'Corolla', 'C-HR', 'RAV4', 'Prius', 'Camry', 'Land Cruiser', 'Hilux', 'Proace'],
  'Volkswagen': ['Polo', 'Golf', 'T-Cross', 'T-Roc', 'Tiguan', 'Passat', 'Touareg', 'ID.3', 'ID.4', 'Caddy', 'Transporter', 'Crafter'],
  'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60', 'V90'],
};

export const getModelsByBrand = (brand: string): string[] => {
  return carModels[brand] || [];
};
