// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjmyfzytcunmzipkbxxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbXlmenl0Y3VubXppcGtieHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjQ1ODMsImV4cCI6MjA1NzY0MDU4M30.gPkDDJuWl2vPjyZOZpdk1caz7jtbgj8SbKdpGbiTxXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);