// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaweocrtnfuannrurvoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhd2VvY3J0bmZ1YW5ucnVydm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzQzMjIsImV4cCI6MjA2MjIxMDMyMn0.y6psfDJr2g3bMyrRQg0Jv9ACCYePSq8mL7UfdNXJDC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);