// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqjwvaqqhqgmkjsriijw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxand2YXFxaHFnbWtqc3JpaWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwOTAyOTYsImV4cCI6MjA1NzY2NjI5Nn0.GyKs7HY6WxdDo7Hf4XZoTQEknNy2pkcZN0ByHq38qMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);